name: "integrity"

on:
  pull_request:
    paths: ["**", "!**.md"]

jobs:
  integrity:
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: "Install dependencies"
        run: npm ci
      - name: "Check code with linter"
        run: npm run lint
      - name: "Build app"
        run: npm run build --if-present
